### ISSUE TITLE
Azure provider should not eixts

### ISSUE THREAD

**Issue by Kannan1015** [MSOpenTech/vagrant-azure#148] opened 2017-01-02 07:21 UTC
When using the below commands the vagrant says setting shouldn't exists; mgmt_endpoint, vm_image.

azure.mgmt_endpoint = 'https://management.core.windows.net'
azure.vm_image='image.vhd'

Can't use any azure properties except subscription id, tenant id, client id and client secret id. Can you suggest whether any configuration missed?

Regards,
Kannan

**Comment by alon-z** [comment] 2017-01-03 12:29
Also here

There are errors in the configuration of this machine. Please fix
the following errors and try again:
Microsoft Azure Provider:
* The following settings shouldn't exist: cloud_service_name, vm_location, vm_user

**Edit**

It looks like some of the options had been changed like:
vm_location -> location
mgmt_endpoint -> endpoint
vm_image -> vm_image_urn

The readme file is outdated

**Comment by devigned** [comment] 2017-02-01 23:59
Which version of vagrant-azure do you have installed?

**Comment by devigned** [comment] 2017-02-20 17:42
Closing. I'm fairly certain this issue is caused by using the 1.x version of the vagrant-azure plugin rather than the 2.x.preview version. Please reopen if this is no the case.

**Closed as completed by devigned** 2017-02-20 17:42 UTC
Labels: question
