### ISSUE TITLE
AuthorizationFailed: The client 'xx' does not have authorization to perform action

### ISSUE THREAD

**Issue by ediri** [MSOpenTech/vagrant-azure#164] opened 2017-02-21 17:35 UTC
Hi all,

i getting these error message, no matter what i try. Can somebody point me to a direction? I can not be the only one otherwhise i am doing something wrong...

```
  "message": "MsRestAzure::AzureOperationError: AuthorizationFailed: The client '9f980a37-5ed1-4731-b836-82fdac7f0906' with object id '9f980a37-5ed1-4731-b836-82fdac7f0906' does not have authorization to perform action 'Microsoft.Compute/locations/publishers/artifacttypes/offers/skus/versions/read' over scope '/subscriptions/aef08ef7-5e7a-441f-b5c7-00897bd3619d'.",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions",
    "method": "get",
    "path_params": {
      "location": "westus",
      "publisherName": "canonical",
      "offer": "ubuntuserver",
      "skus": "16.04.0-LTS",
      "subscriptionId": "aef08ef7-5e7a-441f-b5c7-00897bd3619d"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "$filter": null,
      "$top": null,
      "$orderby": null,
      "api-version": "2016-03-30"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "accept-language": "en-US",
      "x-ms-client-request-id": "2ffdaf3c-6357-42d9-9464-f9b73356ebf2"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client '9f980a37-5ed1-4731-b836-82fdac7f0906' with object id '9f980a37-5ed1-4731-b836-82fdac7f0906' does not have authorization to perform action 'Microsoft.Compute/locations/publishers/artifacttypes/offers/skus/versions/read' over scope '/subscriptions/aef08ef7-5e7a-441f-b5c7-00897bd3619d'.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-request-id": "2338e184-ee89-447f-b0c4-ddcfabc40b5c",
      "x-ms-correlation-request-id": "2338e184-ee89-447f-b0c4-ddcfabc40b5c",
      "x-ms-routing-request-id": "WESTEUROPE:20170221T173057Z:2338e184-ee89-447f-b0c4-ddcfabc40b5c",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Tue, 21 Feb 2017 17:30:56 GMT",
      "connection": "close",
      "content-length": "349"
    },
    "status": 403
  }
}
```

**Comment by devigned** [comment] 2017-02-22 15:10
The service principal you are using doesn't have rights within that tenant. 

Tenants have subscriptions and service principals belong to tenants. Azure resource manager also exposes role based authorization for a given principal, which would give it rights on Azure resources. It appears the service principal doesn't have rights to read from that subscription.

This is a **really** common issue. We've added a specific command in Azure CLI (https://github.com/Azure/azure-cli) to setup a service principal for automation with role based authorization already baked in.

You want to use the `az ad sp create-for-rbac` command.

```
$ az ad sp -h

Group
    az ad sp: Manages AAD service principals for automation authentication.

Commands:
    create
    create-for-rbac  : Create a service principal and configure its access to Azure resources.
    delete
    list
    reset-credentials: Reset credential, on expiration or you forget it.
    show
```

```
$ az ad sp create-for-rbac -h

Command
    az ad sp create-for-rbac: Create a service principal and configure its access to Azure
    resources.

Arguments
    --expanded-view: Once created, display more information like subscription and cloud
                     environments.
    --name -n      : A display name or an app id uri. Command will generate one if missing.
    --password     : The password used to login. If missing, command will generate one.
    --role         : Role the service principal has on the resources.  Default: Contributor.
    --scopes       : Space separated scopes the service principal's role assignment applies to.
                     Defaults to the root of the current subscription.
    --years        : Years the password will be valid.  Default: 1.

Global Arguments
    --debug        : Increase logging verbosity to show all debug logs.
    --help -h      : Show this help message and exit.
    --output -o    : Output format.  Allowed values: json, jsonc, table, tsv.  Default: json.
    --query        : JMESPath query string. See http://jmespath.org/ for more information and
                     examples.
    --verbose      : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Create with defaults
        az ad sp create-for-rbac
    Create with a custom name
        az ad sp create-for-rbac -n "http://my-app"
    Create role assignments at the same time
        az ad sp create-for-rbac -n "http://my-app" --role contributor --scopes
        /subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/mygroup
        /subscriptions/11111111-2222-3333-4444-666666666666/resourceGroups/my-another-group
    Login with this service principal
        az login --service-principal -u <name> -p <password> --tenant <tenant>
    Reset credentials on expiration
        az ad sp reset-credentials --name <name>
    Create role assignments
        az role assignment create --assignee <name> --role Contributor
    Revoke the service principal when done with it
        az ad app delete --id <name>
```

Please let me know if this solved this issue for you.

**Comment by devigned** [comment] 2017-02-28 19:16
I'm closing as I'm fairly certain it's due to RBAC. Please reopen if you feel it's a bug.

**Closed as completed** 2017-02-28 19:16 UTC

**Comment by ediri** [comment] 2017-03-01 07:23
@devigned thanks for the input! we solved yesterday the issue and yes it was a RBAC issue. As soon as we added via CLI the Contributer role to the native app we could perform the actions!

**Comment by devigned** [comment] 2017-03-01 15:36
@ediri, awesome! Glad to hear.

**Comment by zimmertr** [comment] 2017-09-26 19:41
For those coming to this issue, here is how to solve it from the Portal: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

**Comment by rtargosz** [comment] 2018-08-14 19:49
We recently had this issue with the same message and found that it was caused by the user being logged in with a different subscription (we have 2). Using az login --subscription <id> resolved the problem for us.

**Comment by manishkumar1689** [comment] 2018-09-15 15:12
> For those coming to this issue, here is how to solve it from the Portal: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

In this post , Role is given as "Reader" which should be "Owner" instead otherwise it would give permission error on deployment.

**Comment by regisbsb** [comment] 2019-10-20 09:38
I landed here from a google search. If you apply some roles to a principal wait a couple hours before using it.

**Comment by muthukumars** [comment] 2020-01-01 20:44
> The service principal you are using doesn't have rights within that tenant.
> 
> Tenants have subscriptions and service principals belong to tenants. Azure resource manager also exposes role based authorization for a given principal, which would give it rights on Azure resources. It appears the service principal doesn't have rights to read from that subscription.
> 
> This is a **really** common issue. We've added a specific command in Azure CLI (https://github.com/Azure/azure-cli) to setup a service principal for automation with role based authorization already baked in.
> 
> You want to use the `az ad sp create-for-rbac` command.
> 
> ```
> $ az ad sp -h
> 
> Group
>     az ad sp: Manages AAD service principals for automation authentication.
> 
> Commands:
>     create
>     create-for-rbac  : Create a service principal and configure its access to Azure resources.
>     delete
>     list
>     reset-credentials: Reset credential, on expiration or you forget it.
>     show
> ```
> 
> ```
> $ az ad sp create-for-rbac -h
> 
> Command
>     az ad sp create-for-rbac: Create a service principal and configure its access to Azure
>     resources.
> 
> Arguments
>     --expanded-view: Once created, display more information like subscription and cloud
>                      environments.
>     --name -n      : A display name or an app id uri. Command will generate one if missing.
>     --password     : The password used to login. If missing, command will generate one.
>     --role         : Role the service principal has on the resources.  Default: Contributor.
>     --scopes       : Space separated scopes the service principal's role assignment applies to.
>                      Defaults to the root of the current subscription.
>     --years        : Years the password will be valid.  Default: 1.
> 
> Global Arguments
>     --debug        : Increase logging verbosity to show all debug logs.
>     --help -h      : Show this help message and exit.
>     --output -o    : Output format.  Allowed values: json, jsonc, table, tsv.  Default: json.
>     --query        : JMESPath query string. See http://jmespath.org/ for more information and
>                      examples.
>     --verbose      : Increase logging verbosity. Use --debug for full debug logs.
> 
> Examples
>     Create with defaults
>         az ad sp create-for-rbac
>     Create with a custom name
>         az ad sp create-for-rbac -n "http://my-app"
>     Create role assignments at the same time
>         az ad sp create-for-rbac -n "http://my-app" --role contributor --scopes
>         /subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/mygroup
>         /subscriptions/11111111-2222-3333-4444-666666666666/resourceGroups/my-another-group
>     Login with this service principal
>         az login --service-principal -u <name> -p <password> --tenant <tenant>
>     Reset credentials on expiration
>         az ad sp reset-credentials --name <name>
>     Create role assignments
>         az role assignment create --assignee <name> --role Contributor
>     Revoke the service principal when done with it
>         az ad app delete --id <name>
> ```
> 
> Please let me know if this solved this issue for you.

This is awesome. I have spent over two days to figure this out. your quotes were very helpful.

I ran az ad sp create-for-rbac . I expected this to create an "App registrations" under my active directory - Default account. I ran two times so that It creates two. yes. I checked. it created two.

now, I have created "Client Secret" under one of them and got the secrete. with subscriptionid, new client id (with this RBAC app registration), tenant id and client secret, my terraform plan just came out fine with no errors. I have not yet applied though.

My questions:
When I review the app registrations between what I have created manually and through "az ad sp create-for-rbac", I do not see any differences. I checked API permissions. the RBAC app has no permissions. 

though looks like I do not get any more error after RBAC, I would like to know what is the difference between me a) manually created App registrations and b) using this command az ad sp create-for-rbac". Does it give any special permission to use terraform?. How do I check these differences ?

Let me know

**Comment by devigned** [comment] 2020-01-02 16:31
> I ran az ad sp create-for-rbac . I expected this to create an "App registrations" under my active directory - Default account. I ran two times so that It creates two. yes. I checked. it created two.

As it should unless you give it a name, then it should fail on the second due to the name of the principal already exists.

> When I review the app registrations between what I have created manually and through "az ad sp create-for-rbac", I do not see any differences. I checked API permissions. the RBAC app has no permissions.

The difference isn't in the App Registration. The difference in the Azure Role Based Authorization Control (RBAC) which was added in `az ad sp create-for-rbac`, thus the `rbac` in the name of the command.

`az ad sp create-for-rbac` does two things as the documentation states:
1) Create a Service Principal (App and Secret)
2) Configures access to Azure (Applies an RBAC role; in the default case, contributor scoped to the subscription)

If you would like to see the RBAC role, you can view in the portal under Subscription IAM. Search for the name of the Service Principal and you will see that SP has subscription contributor rights.

You could run these two commands yourself through the portal, or even through TF ([Azure Service Bus Golang TF Example](https://github.com/Azure/azure-service-bus-go/blob/1839bfc2a41a03ac130d55a1715188d3c0552f07/azuredeploy.tf#L73-L101)), and you would have the same result. All Azure CLI is doing is manipulating the existing Azure Active Directory and Azure Resource Manager HTTP APIs.

If you ever want to discuss or bounce some questions off me, you can usually find me in gophers.slack.com or devopsengineers.slack.com. I'm alway happy to help. Cheers!

**Comment by muthukumars** [comment] 2020-01-05 03:12
> As it should unless you give it a name, then it should fail on the second due to the name of the principal already exists.

Thank you very much for the insight of this RBAC.  I tried to lookup for a command for giving some name to rbac. I did not get to it or did not have time to look into it. but I see that we can give name. thank you for pointing to me right direction.

az ad sp create-for-rbac [--cert]
                         [--create-cert]
                         [--keyvault]
                         [--name]
                         [--role]
                         [--scopes]
                         [--sdk-auth {false, true}]
                         [--skip-assignment {false, true}]
                         [--years]

-- name will make me to make it as unique so that it does not need to create two times.

I just updated this thread to bring this to closure from my side. I am able to proceed further with my work. Again, thank you very much
