### ISSUE TITLE
Vagrant halt doesn't deallocate vm's

### ISSUE THREAD

**Issue by 4c74356b41** [MSOpenTech/vagrant-azure#179] opened 2017-03-26 18:03 UTC
Am I trippin'? Why would you call `power_off` instead of `deallocate_async`???

https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/virtual_machines.rb#L328

https://github.com/Azure/vagrant-azure/blob/v2.0/lib/vagrant-azure/action/stop_instance.rb#L31

**Comment by devigned** [comment] 2017-03-27 14:56
During deallocate all of the networking infrastructure and scratch disk is reaped. Upon the next start, it would have to be rebuilt. Using power_off, all of the infrastructure stays the same.

Could you explain your preference for deallocate vs power_off? Do you expect to have many long lived deallocated machines?

**Comment by 4c74356b41** [comment] 2017-03-27 16:00
Well, I wasn't planning on using vagrant with azure for production in its current implementations, it looks pretty lacking, to say the least, I was mostly looking to do some tests with it, and the ability to deallocate vm's would help immensely.

Also, can you point me to some docs how to pass custom template to vagrant-azure, I mean, i see there's a switch for that, but how do I pass parameters to that template? Can I pass several templates in a specific order? That might be interesting.

**Comment by devigned** [comment] 2017-03-27 16:42
We accept pull requests :).

I wouldn't recommend using Vagrant for production, generally. I think Vagrant is better poised as a Dev / Test tool rather than a means for deploying production infrastructure (http://stackoverflow.com/a/13616614/134033). I would like to implement Vagrant-Azure push in the future to provide a smooth pathway from Dev / Test to production workloads (https://www.hashicorp.com/blog/vagrant-push-one-command-to-deploy-any-application/).

There are no docs yet for custom deployment templates. The current template is here (https://github.com/Azure/vagrant-azure/blob/v2.0/templates/arm/deployment.json.erb). The parameters are passed in from https://github.com/Azure/vagrant-azure/blob/v2.0/lib/vagrant-azure/action/run_instance.rb. There currently is no way to specify parameters outside of what is passed in via the run_instance action. The parameters required for the template are https://github.com/Azure/vagrant-azure/blob/v2.0/templates/arm/deployment.json.erb#L4-L95. If you were so inclined, you could specify a file location for your custom template and specify it in your Vagrantfile.

I've been ambivalent regarding the existence of the custom deployment template option. I think it makes Vagrant-Azure users need to know more about the underlying workings of Vagrant than they should have to (one box deployment scope with little or no shared state). However, power users might find the constrains imposed by the default infrastructure limiting, so I decided to add it.

As someone who is interested in this feature, what kind of stuff would you like to add that isn't in the existing template? What does your desired infrastructure look like?

**Comment by 4c74356b41** [comment] 2017-03-27 16:58
Well, if it doesn't allow to pass custom parameters it won't really make a lot of sense. It will take some time for me to go through the links you've provided as ruby is obnoxious to say the least. 

Right now there are a lot of gaps, I cant create a VMSS, I cant create Availability set, I can't create from my own vhd (??), but the most frustrating thing is I can't run template deployments, I understand that there are a lot of ways to do that, but that would be a convenient 1 liner to do my own deployments.

If I want to create several VM's in one RG and one VNET it might work and it might fail (depending on how the VNET gets processed).

I don't think it offers dependencies between boxes? The reason for this question is the VNet issue.

**Comment by devigned** [comment] 2017-03-27 17:30
The way Vagrant works, VMSS would be a little odd. We could do it, but the Vagrant box metaphor would be leaky. Vagrant-AWS has not implemented AutoScale Groups for this reason. People build single VMs then use Packer or an equivalent to build custom VHDs to be used in VMSS. With that said, we could build something like the following:
```ruby
Vagrant.configure('2') do |config|

  config.vm.provider :azure do |azure, override|
    azure.multibox_type = 'ScaleSet' # could be ScaleSet or Availability Set
  end

  do_common_azure_stuff = Proc.new do |azure, override|
    override.config.vm.box = 'azure'
    override.vm_image_urn = 'NAME OF THE IMAGE TO USE'
  end

  config.vm.define 'first' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      do_common_azure_stuff.call azure, override
      override.nat = '9220:22'
    end
  end

  config.vm.define 'second' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      do_common_azure_stuff.call azure, override
      override.nat = '9221:22'
    end
  end

  config.vm.define 'third' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      do_common_azure_stuff.call azure, override
      override.nat = '9222:22'
    end
  end

  # Executes powershell on the remote machine and returns the hostname
  config.vm.provision 'shell', inline: 'hostname'

end
```

Per AV Sets, I have a backlog item to add this back. When we moved to ARM, AV Sets didn't make the initial feature set.

You should be able to create a VM from a custom VHD via `vm_image_urn`. If you provide a link to your prepared VHD, it should just work. If there is a bug here, then please open an issue and we'll get it fixed.

If you want to simply run template deployments, why Vagrant? Would the Azure CLI work better for your needs?

**Comment by 4c74356b41** [comment] 2017-03-27 18:01
Well, we might have different opinions on this, but VMSS is a box, I mean, you should manage it as a box, so it is perfectly fine (in my mind) for vagrant. Also, custom script extension should make sense for VMSS (probably for VM also), or some sort of ansible group to configure whole VMSS with 1 "move".

Also, I never insist my cases are super common and super valuable for azure-vagrant, just saying.

But even you mentioned that vagrant-azure is meant for devops\developments, so `vagrant halt` would make perfect sense to deallocate.

**Comment by devigned** [comment] 2017-03-27 18:46
How should `vagrant ssh {box name}` work in the case of VMSS? Should it route to a given machine in VMSS? Should it work at all?

**Comment by 4c74356b41** [comment] 2017-03-27 19:54
well, I guess this is more of an open question,  but this isn't the end of the world, the biggest "challenge" is to create a VMSS, not to ssh\rdp to it ;)

**Comment by 4c74356b41** [comment] 2017-03-30 12:28
to add to this thread, if vm is deallocated vagrant just blows up, `vagrant ssh` doesnt work without any error, `vagrant up` doesn't do anything, `vagrant resume` dies: 

```
Vagrant attempted to call the action 'resume' on the provider
Azure (dfltz:testo1:westeurope), but this provider doesn't support this action.
```

Am I expected never to deallocate a vm? :)

**Comment by devigned** [comment] 2017-03-30 16:31
@4c74356b41 how did you deallocate the machine? Via the portal, PS or CLI?

**Comment by 4c74356b41** [comment] 2017-03-30 17:53
Portal @devigned

**Comment by devigned** [comment] 2017-03-30 19:15
That makes sense why you are experiencing this.

Vagrant is designed to control the lifecycle of the machines. When you de-provision outside of Vagrant, Vagrant still thinks the machine is alive. Thus, when you try to SSH to the machine, you can't connect b/c it can't find an IP associated to the machine (it's been de-provisioned and Vagrant's local cache says it's still provisioned). When you try to call `vagrant up`, Vagrant asks it's local cache and finds out the machine is already up and provisioned, so it does nothing.

I think you'd find the same functionality if you were using Vagrant with a local hypervisor like Hyper-V, Virtual Box, etc.

**Comment by 4c74356b41** [comment] 2017-03-30 20:26
you cant deallocate with vagrant
@devigned

**Comment by devigned** [comment] 2017-04-17 16:44
Deprovisioning takes more time than power down. Rather than change halt to deprovision, we'll introduce `capture` to create an image of the VM. From there, you will be able to create a new VM via `azure.vm_managed_image_id = 'some image id'`. 

I'm going to close this issue as the plugin is working as intended.

**Closed as completed by devigned** 2017-04-17 16:44 UTC
